name: test-extended-configs

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configfile: ["heroku-deploy", "pylint"]
    steps:
    - name: checkout
      uses: actions/checkout@master
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Replace config
      # we could also run a git apply from a diff file...
      # assuming the git apply fails, we know that there's a 'merge' conflict between the config and variants
      run: cp .circleci/extended/${{ matrix.configfile }}.yml .circleci/config.yml
    - name: push-branch
      uses: dsayling/branch-ops-action@v0.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
